/* Generated By:JavaCC: Do not edit this line. parseConstants.java */
package drz.oddb.parse;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface parseConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SEMICOLON = 5;
  /** RegularExpression Id. */
  int CREATE = 6;
  /** RegularExpression Id. */
  int DROP = 7;
  /** RegularExpression Id. */
  int CLASS = 8;
  /** RegularExpression Id. */
  int INSERT = 9;
  /** RegularExpression Id. */
  int INTO = 10;
  /** RegularExpression Id. */
  int VALUES = 11;
  /** RegularExpression Id. */
  int LEFT_BRACKET = 12;
  /** RegularExpression Id. */
  int COMMA = 13;
  /** RegularExpression Id. */
  int RIGHT_BRACKET = 14;
  /** RegularExpression Id. */
  int DELETE = 15;
  /** RegularExpression Id. */
  int FROM = 16;
  /** RegularExpression Id. */
  int WHERE = 17;
  /** RegularExpression Id. */
  int SELECT = 18;
  /** RegularExpression Id. */
  int UNION = 19;
  /** RegularExpression Id. */
  int UNIONSELECT = 20;
  /** RegularExpression Id. */
  int UNIONDEPUTY = 21;
  /** RegularExpression Id. */
  int DEPUTYCLASS = 22;
  /** RegularExpression Id. */
  int SELECTDEPUTY = 23;
  /** RegularExpression Id. */
  int ID = 24;
  /** RegularExpression Id. */
  int EQUAL = 25;
  /** RegularExpression Id. */
  int INT = 26;
  /** RegularExpression Id. */
  int STRING = 27;
  /** RegularExpression Id. */
  int CROSS = 28;
  /** RegularExpression Id. */
  int DOT = 29;
  /** RegularExpression Id. */
  int AS = 30;
  /** RegularExpression Id. */
  int PLUS = 31;
  /** RegularExpression Id. */
  int UPDATE = 32;
  /** RegularExpression Id. */
  int SET = 33;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"/t\"",
    "\"/n\"",
    "\"/r\"",
    "\";\"",
    "\"CREATE\"",
    "\"DROP\"",
    "\"CLASS\"",
    "\"INSERT\"",
    "\"INTO\"",
    "\"VALUES\"",
    "\"(\"",
    "\",\"",
    "\")\"",
    "\"DELETE\"",
    "\"FROM\"",
    "\"WHERE\"",
    "\"SELECT\"",
    "\"UNION\"",
    "\"UNIONSELECT\"",
    "\"UNIONDEPUTY\"",
    "\"DEPUTYCLASS\"",
    "\"SELECTDEPUTY\"",
    "<ID>",
    "\"=\"",
    "<INT>",
    "<STRING>",
    "\"->\"",
    "\".\"",
    "\"AS\"",
    "\"+\"",
    "\"UPDATE\"",
    "\"SET\"",
  };

}
